// Nomenclature des Activités Françaises (NAF rév. 2, 2008) — INSEE
// Source : https://www.insee.fr/fr/information/2406147
// Liste des sous-classes utilisées pour le champ Code NAF à l'inscription.

export interface NafCode {
  code: string
  label: string
  section: string
}

export const NAF_CODES: NafCode[] = [
  // ── A — Agriculture, sylviculture et pêche ──────────────────────────────
  { code: '0111Z', label: 'Culture de céréales, légumineuses et graines oléagineuses', section: 'A' },
  { code: '0112Z', label: 'Culture du riz', section: 'A' },
  { code: '0113Z', label: 'Culture de légumes, melons, racines et tubercules', section: 'A' },
  { code: '0121Z', label: 'Culture de la vigne', section: 'A' },
  { code: '0130Z', label: 'Culture de plantes à épices, aromatiques, médicinales et pharmaceutiques', section: 'A' },
  { code: '0141Z', label: 'Élevage de vaches laitières', section: 'A' },
  { code: '0142Z', label: 'Élevage d\'autres bovins et de buffles', section: 'A' },
  { code: '0150Z', label: 'Culture et élevage associés', section: 'A' },
  { code: '0161Z', label: 'Activités de soutien aux cultures', section: 'A' },
  { code: '0162Z', label: 'Activités de soutien à la production animale', section: 'A' },
  { code: '0210Z', label: 'Sylviculture et autres activités forestières', section: 'A' },
  { code: '0311Z', label: 'Pêche en mer', section: 'A' },
  { code: '0321Z', label: 'Aquaculture en mer', section: 'A' },

  // ── B — Industries extractives ──────────────────────────────────────────
  { code: '0610Z', label: 'Extraction de pétrole brut', section: 'B' },
  { code: '0710Z', label: 'Extraction de minerais de fer', section: 'B' },
  { code: '0891Z', label: 'Extraction des minéraux chimiques et engrais minéraux', section: 'B' },

  // ── C — Industrie manufacturière ────────────────────────────────────────
  { code: '1011Z', label: 'Transformation et conservation de la viande de boucherie', section: 'C' },
  { code: '1013A', label: 'Préparation industrielle de produits à base de viande', section: 'C' },
  { code: '1041A', label: 'Fabrication d\'huiles et graisses brutes', section: 'C' },
  { code: '1051A', label: 'Fabrication de lait liquide et de produits frais', section: 'C' },
  { code: '1061A', label: 'Meunerie', section: 'C' },
  { code: '1071A', label: 'Fabrication industrielle de pain et de pâtisserie fraîche', section: 'C' },
  { code: '1071B', label: 'Cuisson de produits de boulangerie-pâtisserie', section: 'C' },
  { code: '1071C', label: 'Boulangerie et boulangerie-pâtisserie', section: 'C' },
  { code: '1071D', label: 'Pâtisserie', section: 'C' },
  { code: '1086Z', label: 'Fabrication d\'aliments homogénéisés et diététiques', section: 'C' },
  { code: '1101Z', label: 'Production de boissons alcooliques distillées', section: 'C' },
  { code: '1102A', label: 'Fabrication de vins effervescents', section: 'C' },
  { code: '1102B', label: 'Vinification', section: 'C' },
  { code: '1107A', label: 'Industrie des eaux de table', section: 'C' },
  { code: '1200Z', label: 'Fabrication de produits à base de tabac', section: 'C' },
  { code: '1310Z', label: 'Préparation de fibres textiles et filature', section: 'C' },
  { code: '1393Z', label: 'Fabrication de tapis et moquettes', section: 'C' },
  { code: '1411Z', label: 'Fabrication de vêtements en cuir', section: 'C' },
  { code: '1412Z', label: 'Fabrication de vêtements de travail', section: 'C' },
  { code: '1413Z', label: 'Fabrication de vêtements de dessus', section: 'C' },
  { code: '1419Z', label: 'Fabrication d\'autres vêtements et accessoires', section: 'C' },
  { code: '1420Z', label: 'Fabrication d\'articles en fourrure', section: 'C' },
  { code: '1511Z', label: 'Apprêt et tannage des cuirs', section: 'C' },
  { code: '1520Z', label: 'Fabrication de chaussures', section: 'C' },
  { code: '1610A', label: 'Sciage et rabotage du bois', section: 'C' },
  { code: '1623Z', label: 'Fabrication de charpentes et d\'autres menuiseries', section: 'C' },
  { code: '1624Z', label: 'Fabrication d\'emballages en bois', section: 'C' },
  { code: '1629Z', label: 'Fabrication d\'objets divers en bois; en liège, vannerie et sparterie', section: 'C' },
  { code: '1711Z', label: 'Fabrication de pâte à papier', section: 'C' },
  { code: '1712Z', label: 'Fabrication de papier et de carton', section: 'C' },
  { code: '1721A', label: 'Fabrication de carton ondulé', section: 'C' },
  { code: '1811Z', label: 'Imprimerie de journaux', section: 'C' },
  { code: '1812Z', label: 'Autre imprimerie', section: 'C' },
  { code: '1813Z', label: 'Activités de pré-presse', section: 'C' },
  { code: '1814Z', label: 'Reliure et activités connexes', section: 'C' },
  { code: '2011Z', label: 'Fabrication de gaz industriels', section: 'C' },
  { code: '2016Z', label: 'Fabrication de matières plastiques de base', section: 'C' },
  { code: '2059Z', label: 'Fabrication d\'autres produits chimiques n.c.a.', section: 'C' },
  { code: '2110Z', label: 'Fabrication de produits pharmaceutiques de base', section: 'C' },
  { code: '2120Z', label: 'Fabrication de médicaments', section: 'C' },
  { code: '2211Z', label: 'Fabrication et rechapage de pneumatiques', section: 'C' },
  { code: '2219Z', label: 'Fabrication d\'autres articles en caoutchouc', section: 'C' },
  { code: '2221Z', label: 'Fabrication de plaques, feuilles, tubes et profilés en matières plastiques', section: 'C' },
  { code: '2229A', label: 'Fabrication de pièces techniques à base de matières plastiques', section: 'C' },
  { code: '2311Z', label: 'Fabrication de verre plat', section: 'C' },
  { code: '2351Z', label: 'Fabrication de ciment', section: 'C' },
  { code: '2399Z', label: 'Fabrication d\'autres produits minéraux non métalliques n.c.a.', section: 'C' },
  { code: '2410Z', label: 'Sidérurgie', section: 'C' },
  { code: '2511Z', label: 'Fabrication de structures métalliques et de parties de structures', section: 'C' },
  { code: '2512Z', label: 'Fabrication de portes et fenêtres en métal', section: 'C' },
  { code: '2561Z', label: 'Traitement et revêtement des métaux', section: 'C' },
  { code: '2562B', label: 'Mécanique industrielle', section: 'C' },
  { code: '2571Z', label: 'Fabrication de coutellerie', section: 'C' },
  { code: '2572Z', label: 'Fabrication de serrures et de ferrures', section: 'C' },
  { code: '2573A', label: 'Fabrication de moules et modèles', section: 'C' },
  { code: '2591Z', label: 'Fabrication de fûts et emballages métalliques similaires', section: 'C' },
  { code: '2611Z', label: 'Fabrication de composants électroniques', section: 'C' },
  { code: '2620Z', label: 'Fabrication d\'ordinateurs et d\'équipements périphériques', section: 'C' },
  { code: '2630Z', label: 'Fabrication d\'équipements de communication', section: 'C' },
  { code: '2640Z', label: 'Fabrication de produits électroniques grand public', section: 'C' },
  { code: '2660Z', label: 'Fabrication d\'équipements d\'irradiation médicale, électromédicaux et électrothérapeutiques', section: 'C' },
  { code: '2711Z', label: 'Fabrication de moteurs, génératrices et transformateurs électriques', section: 'C' },
  { code: '2712Z', label: 'Fabrication de matériel de distribution et de commande électrique', section: 'C' },
  { code: '2731Z', label: 'Fabrication de câbles de fibres optiques', section: 'C' },
  { code: '2740Z', label: 'Fabrication d\'appareils d\'éclairage électrique', section: 'C' },
  { code: '2751Z', label: 'Fabrication d\'appareils électroménagers', section: 'C' },
  { code: '2811Z', label: 'Fabrication de moteurs et turbines, à l\'exception des moteurs d\'avions et de véhicules', section: 'C' },
  { code: '2841Z', label: 'Fabrication de machines-outils pour le travail des métaux', section: 'C' },
  { code: '2910Z', label: 'Construction de véhicules automobiles', section: 'C' },
  { code: '2920Z', label: 'Fabrication de carrosseries et remorques', section: 'C' },
  { code: '2932Z', label: 'Fabrication d\'autres équipements automobiles', section: 'C' },
  { code: '3011Z', label: 'Construction de navires et de structures flottantes', section: 'C' },
  { code: '3030Z', label: 'Construction aéronautique et spatiale', section: 'C' },
  { code: '3101Z', label: 'Fabrication de meubles de bureau et de magasin', section: 'C' },
  { code: '3102Z', label: 'Fabrication de meubles de cuisine', section: 'C' },
  { code: '3109A', label: 'Fabrication de sièges d\'ameublement d\'intérieur', section: 'C' },
  { code: '3109B', label: 'Fabrication d\'autres meubles et industries connexes de l\'ameublement', section: 'C' },

  // ── D — Production et distribution d'énergie ────────────────────────────
  { code: '3511Z', label: 'Production d\'électricité', section: 'D' },
  { code: '3512Z', label: 'Transport d\'électricité', section: 'D' },
  { code: '3521Z', label: 'Production de gaz', section: 'D' },

  // ── E — Eau, assainissement, déchets ────────────────────────────────────
  { code: '3600Z', label: 'Captage, traitement et distribution d\'eau', section: 'E' },
  { code: '3700Z', label: 'Collecte et traitement des eaux usées', section: 'E' },
  { code: '3811Z', label: 'Collecte des déchets non dangereux', section: 'E' },
  { code: '3812Z', label: 'Collecte des déchets dangereux', section: 'E' },
  { code: '3821Z', label: 'Traitement et élimination des déchets non dangereux', section: 'E' },
  { code: '3900Z', label: 'Dépollution et autres services de gestion des déchets', section: 'E' },

  // ── F — Construction ────────────────────────────────────────────────────
  { code: '4110A', label: 'Promotion immobilière de logements', section: 'F' },
  { code: '4110B', label: 'Promotion immobilière de bureaux', section: 'F' },
  { code: '4110C', label: 'Promotion immobilière d\'autres bâtiments', section: 'F' },
  { code: '4110D', label: 'Supports juridiques de programmes', section: 'F' },
  { code: '4120A', label: 'Construction de maisons individuelles', section: 'F' },
  { code: '4120B', label: 'Construction d\'autres bâtiments résidentiels', section: 'F' },
  { code: '4211Z', label: 'Construction de routes et autoroutes', section: 'F' },
  { code: '4213A', label: 'Construction d\'ouvrages d\'art', section: 'F' },
  { code: '4221Z', label: 'Construction de réseaux pour fluides', section: 'F' },
  { code: '4299Z', label: 'Construction d\'autres ouvrages de génie civil n.c.a.', section: 'F' },
  { code: '4311Z', label: 'Travaux de démolition', section: 'F' },
  { code: '4312A', label: 'Travaux de terrassement courants et travaux préparatoires', section: 'F' },
  { code: '4321A', label: 'Travaux d\'installation électrique dans tous locaux', section: 'F' },
  { code: '4321B', label: 'Travaux d\'installation électrique sur la voie publique', section: 'F' },
  { code: '4322A', label: 'Travaux d\'installation d\'eau et de gaz en tous locaux', section: 'F' },
  { code: '4322B', label: 'Travaux d\'installation d\'équipements thermiques et de climatisation', section: 'F' },
  { code: '4329A', label: 'Travaux d\'isolation', section: 'F' },
  { code: '4331Z', label: 'Travaux de plâtrerie', section: 'F' },
  { code: '4332A', label: 'Travaux de menuiserie bois et PVC', section: 'F' },
  { code: '4332B', label: 'Travaux de menuiserie métallique et serrurerie', section: 'F' },
  { code: '4333Z', label: 'Travaux de revêtement des sols et des murs', section: 'F' },
  { code: '4334Z', label: 'Travaux de peinture et vitrerie', section: 'F' },
  { code: '4339Z', label: 'Autres travaux de finition', section: 'F' },
  { code: '4391A', label: 'Travaux de charpente', section: 'F' },
  { code: '4391B', label: 'Travaux de couverture par éléments', section: 'F' },
  { code: '4399A', label: 'Travaux d\'étanchéification', section: 'F' },
  { code: '4399C', label: 'Travaux de maçonnerie générale et gros œuvre de bâtiment', section: 'F' },

  // ── G — Commerce; réparation automobiles ────────────────────────────────
  { code: '4511Z', label: 'Commerce de voitures et de véhicules automobiles légers', section: 'G' },
  { code: '4520A', label: 'Entretien et réparation de véhicules automobiles légers', section: 'G' },
  { code: '4520B', label: 'Entretien et réparation d\'autres véhicules automobiles', section: 'G' },
  { code: '4531Z', label: 'Commerce de gros d\'équipements automobiles', section: 'G' },
  { code: '4540Z', label: 'Commerce et réparation de motocycles', section: 'G' },
  { code: '4611Z', label: 'Intermédiaires du commerce en matières premières agricoles, animaux vivants, matières premières textiles et produits semi-finis', section: 'G' },
  { code: '4619A', label: 'Centrale d\'achat alimentaire', section: 'G' },
  { code: '4621Z', label: 'Commerce de gros de céréales, de tabac non manufacturé, de semences et d\'aliments pour le bétail', section: 'G' },
  { code: '4631Z', label: 'Commerce de gros de fruits et légumes', section: 'G' },
  { code: '4632A', label: 'Commerce de gros de viandes de boucherie', section: 'G' },
  { code: '4634Z', label: 'Commerce de gros de boissons', section: 'G' },
  { code: '4641Z', label: 'Commerce de gros de textiles', section: 'G' },
  { code: '4645Z', label: 'Commerce de gros de parfumerie et de produits de beauté', section: 'G' },
  { code: '4647Z', label: 'Commerce de gros de meubles, de tapis et d\'appareils d\'éclairage', section: 'G' },
  { code: '4649Z', label: 'Commerce de gros d\'autres biens domestiques', section: 'G' },
  { code: '4651Z', label: 'Commerce de gros d\'ordinateurs, d\'équipements informatiques périphériques et de logiciels', section: 'G' },
  { code: '4652Z', label: 'Commerce de gros de composants et d\'équipements électroniques et de télécommunication', section: 'G' },
  { code: '4661Z', label: 'Commerce de gros de matériel agricole', section: 'G' },
  { code: '4662Z', label: 'Commerce de gros de machines-outils', section: 'G' },
  { code: '4669B', label: 'Commerce de gros de fournitures et équipements industriels divers', section: 'G' },
  { code: '4671Z', label: 'Commerce de gros de combustibles et de produits annexes', section: 'G' },
  { code: '4690Z', label: 'Commerce de gros non spécialisé', section: 'G' },
  { code: '4711B', label: 'Commerce d\'alimentation générale', section: 'G' },
  { code: '4711C', label: 'Supérettes', section: 'G' },
  { code: '4711D', label: 'Supermarchés', section: 'G' },
  { code: '4711E', label: 'Hypermarchés', section: 'G' },
  { code: '4711F', label: 'Commerces de détail de surgelés', section: 'G' },
  { code: '4719A', label: 'Grands magasins', section: 'G' },
  { code: '4719B', label: 'Autres commerces de détail en magasin non spécialisé', section: 'G' },
  { code: '4721Z', label: 'Commerce de détail de fruits et légumes en magasin spécialisé', section: 'G' },
  { code: '4722Z', label: 'Commerce de détail de viandes et de produits à base de viande en magasin spécialisé', section: 'G' },
  { code: '4724Z', label: 'Commerce de détail de pain, pâtisserie et confiserie en magasin spécialisé', section: 'G' },
  { code: '4725Z', label: 'Commerce de détail de boissons en magasin spécialisé', section: 'G' },
  { code: '4726Z', label: 'Commerce de détail de produits à base de tabac en magasin spécialisé', section: 'G' },
  { code: '4729Z', label: 'Autres commerces de détail alimentaires en magasin spécialisé', section: 'G' },
  { code: '4730Z', label: 'Commerce de détail de carburants en magasin spécialisé', section: 'G' },
  { code: '4741Z', label: 'Commerce de détail d\'ordinateurs, d\'unités périphériques et de logiciels en magasin spécialisé', section: 'G' },
  { code: '4742Z', label: 'Commerce de détail de matériels de télécommunication en magasin spécialisé', section: 'G' },
  { code: '4751Z', label: 'Commerce de détail de textiles en magasin spécialisé', section: 'G' },
  { code: '4752A', label: 'Commerce de détail de quincaillerie, peintures et verres en petites surfaces', section: 'G' },
  { code: '4752B', label: 'Commerce de détail de quincaillerie, peintures et verres en grandes surfaces', section: 'G' },
  { code: '4753Z', label: 'Commerce de détail de tapis, moquettes et revêtements de murs et de sols en magasin spécialisé', section: 'G' },
  { code: '4754Z', label: 'Commerce de détail d\'appareils électroménagers en magasin spécialisé', section: 'G' },
  { code: '4759A', label: 'Commerce de détail de meubles', section: 'G' },
  { code: '4761Z', label: 'Commerce de détail de livres en magasin spécialisé', section: 'G' },
  { code: '4762Z', label: 'Commerce de détail de journaux et papeterie en magasin spécialisé', section: 'G' },
  { code: '4763Z', label: 'Commerce de détail d\'enregistrements musicaux et vidéo en magasin spécialisé', section: 'G' },
  { code: '4764Z', label: 'Commerce de détail d\'articles de sport en magasin spécialisé', section: 'G' },
  { code: '4765Z', label: 'Commerce de détail de jeux et jouets en magasin spécialisé', section: 'G' },
  { code: '4771Z', label: 'Commerce de détail d\'habillement en magasin spécialisé', section: 'G' },
  { code: '4772A', label: 'Commerce de détail de la chaussure', section: 'G' },
  { code: '4773Z', label: 'Commerce de détail de produits pharmaceutiques en magasin spécialisé', section: 'G' },
  { code: '4774Z', label: 'Commerce de détail d\'articles médicaux et orthopédiques en magasin spécialisé', section: 'G' },
  { code: '4775Z', label: 'Commerce de détail de parfumerie et de produits de beauté en magasin spécialisé', section: 'G' },
  { code: '4776Z', label: 'Commerce de détail de fleurs, plantes, graines, engrais, animaux de compagnie et aliments pour ces animaux en magasin spécialisé', section: 'G' },
  { code: '4777Z', label: 'Commerce de détail d\'articles d\'horlogerie et de bijouterie en magasin spécialisé', section: 'G' },
  { code: '4781Z', label: 'Commerce de détail alimentaire sur éventaires et marchés', section: 'G' },
  { code: '4782Z', label: 'Commerce de détail de textiles, d\'habillement et de chaussures sur éventaires et marchés', section: 'G' },
  { code: '4791A', label: 'Vente à distance sur catalogue général', section: 'G' },
  { code: '4791B', label: 'Vente à distance sur catalogue spécialisé', section: 'G' },
  { code: '4799A', label: 'Vente à domicile', section: 'G' },

  // ── H — Transports et entreposage ───────────────────────────────────────
  { code: '4910Z', label: 'Transport ferroviaire interurbain de voyageurs', section: 'H' },
  { code: '4920Z', label: 'Transport de fret ferroviaire', section: 'H' },
  { code: '4931Z', label: 'Transports urbains et suburbains de voyageurs', section: 'H' },
  { code: '4932Z', label: 'Transports de voyageurs par taxis', section: 'H' },
  { code: '4939A', label: 'Transports routiers réguliers de voyageurs', section: 'H' },
  { code: '4939B', label: 'Autres transports routiers de voyageurs', section: 'H' },
  { code: '4941A', label: 'Transports routiers de fret interurbains', section: 'H' },
  { code: '4941B', label: 'Transports routiers de fret de proximité', section: 'H' },
  { code: '4941C', label: 'Location de camions avec chauffeur', section: 'H' },
  { code: '4942Z', label: 'Services de déménagement', section: 'H' },
  { code: '4950Z', label: 'Transports par conduites', section: 'H' },
  { code: '5010Z', label: 'Transports maritimes et côtiers de passagers', section: 'H' },
  { code: '5020Z', label: 'Transports maritimes et côtiers de fret', section: 'H' },
  { code: '5110Z', label: 'Transports aériens de passagers', section: 'H' },
  { code: '5210A', label: 'Entreposage et stockage frigorifique', section: 'H' },
  { code: '5210B', label: 'Entreposage et stockage non frigorifique', section: 'H' },
  { code: '5221Z', label: 'Services auxiliaires des transports terrestres', section: 'H' },
  { code: '5222Z', label: 'Services auxiliaires des transports par eau', section: 'H' },
  { code: '5229A', label: 'Messagerie, fret express', section: 'H' },
  { code: '5229B', label: 'Affrètement et organisation des transports', section: 'H' },
  { code: '5310Z', label: 'Activités de poste dans le cadre d\'une obligation de service universel', section: 'H' },
  { code: '5320Z', label: 'Autres activités de poste et de courrier', section: 'H' },

  // ── I — Hébergement et restauration ─────────────────────────────────────
  { code: '5510Z', label: 'Hôtels et hébergement similaire', section: 'I' },
  { code: '5520Z', label: 'Hébergement touristique et autre hébergement de courte durée', section: 'I' },
  { code: '5530Z', label: 'Terrains de camping et parcs pour caravanes ou véhicules de loisirs', section: 'I' },
  { code: '5590Z', label: 'Autres hébergements', section: 'I' },
  { code: '5610A', label: 'Restauration traditionnelle', section: 'I' },
  { code: '5610B', label: 'Cafétérias et autres libres-services', section: 'I' },
  { code: '5610C', label: 'Restauration de type rapide', section: 'I' },
  { code: '5621Z', label: 'Services des traiteurs', section: 'I' },
  { code: '5629A', label: 'Restauration collective sous contrat', section: 'I' },
  { code: '5629B', label: 'Autres services de restauration n.c.a.', section: 'I' },
  { code: '5630Z', label: 'Débits de boissons', section: 'I' },

  // ── J — Information et communication ────────────────────────────────────
  { code: '5811Z', label: 'Édition de livres', section: 'J' },
  { code: '5812Z', label: 'Édition de répertoires et de fichiers d\'adresses', section: 'J' },
  { code: '5813Z', label: 'Édition de journaux', section: 'J' },
  { code: '5814Z', label: 'Édition de revues et périodiques', section: 'J' },
  { code: '5819Z', label: 'Autres activités d\'édition', section: 'J' },
  { code: '5821Z', label: 'Édition de jeux électroniques', section: 'J' },
  { code: '5829A', label: 'Édition de logiciels système et de réseau', section: 'J' },
  { code: '5829B', label: 'Édition de logiciels outils de développement et de langages', section: 'J' },
  { code: '5829C', label: 'Édition de logiciels applicatifs', section: 'J' },
  { code: '5911A', label: 'Production de films et de programmes pour la télévision', section: 'J' },
  { code: '5911B', label: 'Production de films institutionnels et publicitaires', section: 'J' },
  { code: '5911C', label: 'Production de films pour le cinéma', section: 'J' },
  { code: '5912Z', label: 'Post-production de films cinématographiques, de vidéo et de programmes de télévision', section: 'J' },
  { code: '5913A', label: 'Distribution de films cinématographiques', section: 'J' },
  { code: '6010Z', label: 'Édition et diffusion de programmes radio', section: 'J' },
  { code: '6020A', label: 'Edition de chaînes généralistes', section: 'J' },
  { code: '6110Z', label: 'Télécommunications filaires', section: 'J' },
  { code: '6120Z', label: 'Télécommunications sans fil', section: 'J' },
  { code: '6130Z', label: 'Télécommunications par satellite', section: 'J' },
  { code: '6190Z', label: 'Autres activités de télécommunication', section: 'J' },
  { code: '6201Z', label: 'Programmation informatique', section: 'J' },
  { code: '6202A', label: 'Conseil en systèmes et logiciels informatiques', section: 'J' },
  { code: '6202B', label: 'Tierce maintenance de systèmes et d\'applications informatiques', section: 'J' },
  { code: '6203Z', label: 'Gestion d\'installations informatiques', section: 'J' },
  { code: '6209Z', label: 'Autres activités informatiques', section: 'J' },
  { code: '6311Z', label: 'Traitement de données, hébergement et activités connexes', section: 'J' },
  { code: '6312Z', label: 'Portails Internet', section: 'J' },
  { code: '6391Z', label: 'Activités des agences de presse', section: 'J' },
  { code: '6399Z', label: 'Autres services d\'information n.c.a.', section: 'J' },

  // ── K — Activités financières et d'assurance ────────────────────────────
  { code: '6411Z', label: 'Activités de banque centrale', section: 'K' },
  { code: '6419Z', label: 'Autres intermédiations monétaires', section: 'K' },
  { code: '6420Z', label: 'Activités des sociétés holding', section: 'K' },
  { code: '6430Z', label: 'Fonds de placement et entités financières similaires', section: 'K' },
  { code: '6491Z', label: 'Crédit-bail', section: 'K' },
  { code: '6492Z', label: 'Autre distribution de crédit', section: 'K' },
  { code: '6499Z', label: 'Autres activités des services financiers, hors assurance et caisses de retraite, n.c.a.', section: 'K' },
  { code: '6511Z', label: 'Assurance vie', section: 'K' },
  { code: '6512Z', label: 'Autres assurances', section: 'K' },
  { code: '6520Z', label: 'Réassurance', section: 'K' },
  { code: '6622Z', label: 'Activités des agents et courtiers d\'assurances', section: 'K' },
  { code: '6630Z', label: 'Gestion de fonds', section: 'K' },

  // ── L — Activités immobilières ───────────────────────────────────────────
  { code: '6810Z', label: 'Activités des marchands de biens immobiliers', section: 'L' },
  { code: '6820A', label: 'Location de logements', section: 'L' },
  { code: '6820B', label: 'Location de terrains et d\'autres biens immobiliers', section: 'L' },
  { code: '6831Z', label: 'Agences immobilières', section: 'L' },
  { code: '6832A', label: 'Administration d\'immeubles et autres biens immobiliers', section: 'L' },

  // ── M — Activités spécialisées, scientifiques et techniques ─────────────
  { code: '6910Z', label: 'Activités juridiques', section: 'M' },
  { code: '6920Z', label: 'Activités comptables', section: 'M' },
  { code: '7010Z', label: 'Activités des sièges sociaux', section: 'M' },
  { code: '7021Z', label: 'Conseil en relations publiques et communication', section: 'M' },
  { code: '7022Z', label: 'Conseil pour les affaires et autres conseils de gestion', section: 'M' },
  { code: '7111Z', label: 'Activités d\'architecture', section: 'M' },
  { code: '7112A', label: 'Activité des géomètres', section: 'M' },
  { code: '7112B', label: 'Ingénierie, études techniques', section: 'M' },
  { code: '7120A', label: 'Contrôle technique automobile', section: 'M' },
  { code: '7120B', label: 'Analyses, essais et inspections techniques', section: 'M' },
  { code: '7211Z', label: 'Recherche-développement en biotechnologie', section: 'M' },
  { code: '7219Z', label: 'Recherche-développement en autres sciences physiques et naturelles', section: 'M' },
  { code: '7220Z', label: 'Recherche-développement en sciences humaines et sociales', section: 'M' },
  { code: '7311Z', label: 'Activités des agences de publicité', section: 'M' },
  { code: '7312Z', label: 'Régie publicitaire de médias', section: 'M' },
  { code: '7320Z', label: 'Études de marché et sondages', section: 'M' },
  { code: '7410Z', label: 'Activités spécialisées de design', section: 'M' },
  { code: '7420Z', label: 'Activités photographiques', section: 'M' },
  { code: '7430Z', label: 'Traduction et interprétation', section: 'M' },
  { code: '7490A', label: 'Activité des économistes de la construction', section: 'M' },
  { code: '7490B', label: 'Activités spécialisées, scientifiques et techniques diverses', section: 'M' },
  { code: '7500Z', label: 'Activités vétérinaires', section: 'M' },
  { code: '7711A', label: 'Location de courte durée de voitures et de véhicules automobiles légers', section: 'M' },
  { code: '7711B', label: 'Location de longue durée de voitures et de véhicules automobiles légers', section: 'M' },
  { code: '7712Z', label: 'Location et location-bail de camions', section: 'M' },
  { code: '7733Z', label: 'Location et location-bail de machines de bureau et de matériel informatique', section: 'M' },
  { code: '7740Z', label: 'Location-bail de propriété intellectuelle et de produits similaires, à l\'exception des œuvres soumises à copyright', section: 'M' },

  // ── N — Activités de services administratifs et de soutien ──────────────
  { code: '7810Z', label: 'Activités des agences de placement de main-d\'œuvre', section: 'N' },
  { code: '7820Z', label: 'Activités des agences de travail temporaire', section: 'N' },
  { code: '7830Z', label: 'Autre mise à disposition de ressources humaines', section: 'N' },
  { code: '7911Z', label: 'Activités des agences de voyage', section: 'N' },
  { code: '7912Z', label: 'Activités des voyagistes', section: 'N' },
  { code: '7990Z', label: 'Autres services de réservation et activités connexes', section: 'N' },
  { code: '8010Z', label: 'Activités de sécurité privée', section: 'N' },
  { code: '8020Z', label: 'Activités liées aux systèmes de sécurité', section: 'N' },
  { code: '8030Z', label: 'Activités d\'enquête', section: 'N' },
  { code: '8110Z', label: 'Activités combinées de soutien lié aux bâtiments', section: 'N' },
  { code: '8121Z', label: 'Nettoyage courant des bâtiments', section: 'N' },
  { code: '8122Z', label: 'Autres activités de nettoyage des bâtiments et nettoyage industriel', section: 'N' },
  { code: '8129A', label: 'Désinfection, désinsectisation, dératisation', section: 'N' },
  { code: '8129B', label: 'Autres activités de nettoyage n.c.a.', section: 'N' },
  { code: '8130Z', label: 'Services d\'aménagement paysager', section: 'N' },
  { code: '8211Z', label: 'Services administratifs combinés de bureau', section: 'N' },
  { code: '8219Z', label: 'Photocopie, préparation de documents et autres activités spécialisées de soutien de bureau', section: 'N' },
  { code: '8220Z', label: 'Activités de centres d\'appels', section: 'N' },
  { code: '8230Z', label: 'Organisation de foires, salons professionnels et congrès', section: 'N' },
  { code: '8291Z', label: 'Activités des agences de recouvrement de factures et des sociétés d\'information financière sur la clientèle', section: 'N' },
  { code: '8292Z', label: 'Activités de conditionnement', section: 'N' },
  { code: '8299Z', label: 'Autres activités de soutien aux entreprises n.c.a.', section: 'N' },

  // ── O — Administration publique ──────────────────────────────────────────
  { code: '8411Z', label: 'Administration publique générale', section: 'O' },
  { code: '8412Z', label: 'Administration publique (tutelle) de la santé, de la formation, de la culture et des services sociaux', section: 'O' },
  { code: '8413Z', label: 'Administration publique (tutelle) des activités économiques', section: 'O' },

  // ── P — Enseignement ─────────────────────────────────────────────────────
  { code: '8510Z', label: 'Enseignement pré-primaire', section: 'P' },
  { code: '8520Z', label: 'Enseignement primaire', section: 'P' },
  { code: '8531Z', label: 'Enseignement secondaire général', section: 'P' },
  { code: '8532Z', label: 'Enseignement secondaire technique ou professionnel', section: 'P' },
  { code: '8541Z', label: 'Enseignement post-secondaire non supérieur', section: 'P' },
  { code: '8542Z', label: 'Enseignement supérieur', section: 'P' },
  { code: '8551Z', label: 'Enseignement de disciplines sportives et d\'activités de loisirs', section: 'P' },
  { code: '8552Z', label: 'Enseignement culturel', section: 'P' },
  { code: '8553Z', label: 'Enseignement de la conduite', section: 'P' },
  { code: '8559A', label: 'Formation continue d\'adultes', section: 'P' },
  { code: '8559B', label: 'Autres enseignements', section: 'P' },
  { code: '8560Z', label: 'Activités de soutien à l\'enseignement', section: 'P' },

  // ── Q — Santé humaine et action sociale ──────────────────────────────────
  { code: '8610Z', label: 'Activités hospitalières', section: 'Q' },
  { code: '8621Z', label: 'Activité des médecins généralistes', section: 'Q' },
  { code: '8622A', label: 'Activités de radiodiagnostic et de radiothérapie', section: 'Q' },
  { code: '8622B', label: 'Activités chirurgicales', section: 'Q' },
  { code: '8622C', label: 'Autres activités des médecins spécialistes', section: 'Q' },
  { code: '8623Z', label: 'Pratique dentaire', section: 'Q' },
  { code: '8690A', label: 'Ambulances', section: 'Q' },
  { code: '8690B', label: 'Laboratoires d\'analyses médicales', section: 'Q' },
  { code: '8690C', label: 'Centres de collecte et banques d\'organes', section: 'Q' },
  { code: '8690D', label: 'Activités des infirmiers et des sages-femmes', section: 'Q' },
  { code: '8690E', label: 'Activités des professionnels de la rééducation, de l\'appareillage et des pédicures-podologues', section: 'Q' },
  { code: '8690F', label: 'Activités de santé humaine non classées ailleurs', section: 'Q' },
  { code: '8710A', label: 'Hébergement médicalisé pour personnes âgées', section: 'Q' },
  { code: '8710B', label: 'Hébergement médicalisé pour enfants handicapés', section: 'Q' },
  { code: '8710C', label: 'Hébergement médicalisé pour adultes handicapés et autre hébergement médicalisé', section: 'Q' },
  { code: '8720A', label: 'Hébergement social pour handicapés mentaux et malades mentaux', section: 'Q' },
  { code: '8790A', label: 'Hébergement social pour enfants en difficultés', section: 'Q' },
  { code: '8810A', label: 'Aide à domicile', section: 'Q' },
  { code: '8810B', label: 'Accueil ou accompagnement sans hébergement d\'adultes handicapés ou de personnes âgées', section: 'Q' },
  { code: '8810C', label: 'Aide par le travail', section: 'Q' },
  { code: '8891A', label: 'Accueil de jeunes enfants', section: 'Q' },
  { code: '8891B', label: 'Accueil ou accompagnement sans hébergement d\'enfants handicapés', section: 'Q' },
  { code: '8899A', label: 'Autre accueil ou accompagnement sans hébergement d\'enfants et d\'adolescents', section: 'Q' },
  { code: '8899B', label: 'Action sociale sans hébergement n.c.a.', section: 'Q' },

  // ── R — Arts, spectacles et activités récréatives ────────────────────────
  { code: '9001Z', label: 'Arts du spectacle vivant', section: 'R' },
  { code: '9002Z', label: 'Activités de soutien au spectacle vivant', section: 'R' },
  { code: '9003A', label: 'Création artistique relevant des arts plastiques', section: 'R' },
  { code: '9003B', label: 'Autre création artistique', section: 'R' },
  { code: '9004Z', label: 'Gestion de salles de spectacles', section: 'R' },
  { code: '9101Z', label: 'Gestion des bibliothèques et des archives', section: 'R' },
  { code: '9102Z', label: 'Gestion des musées', section: 'R' },
  { code: '9103Z', label: 'Gestion des sites et monuments historiques et des attractions touristiques similaires', section: 'R' },
  { code: '9200Z', label: 'Organisation de jeux de hasard et d\'argent', section: 'R' },
  { code: '9311Z', label: 'Gestion d\'installations sportives', section: 'R' },
  { code: '9312Z', label: 'Activités de clubs de sports', section: 'R' },
  { code: '9313Z', label: 'Activités des centres de culture physique', section: 'R' },
  { code: '9319Z', label: 'Autres activités liées au sport', section: 'R' },
  { code: '9321Z', label: 'Activités des parcs d\'attractions et parcs à thèmes', section: 'R' },
  { code: '9329Z', label: 'Autres activités récréatives et de loisirs', section: 'R' },

  // ── S — Autres activités de services ────────────────────────────────────
  { code: '9411Z', label: 'Activités des organisations patronales et consulaires', section: 'S' },
  { code: '9412Z', label: 'Activités des organisations professionnelles', section: 'S' },
  { code: '9420Z', label: 'Activités des syndicats de salariés', section: 'S' },
  { code: '9491Z', label: 'Activités des organisations religieuses', section: 'S' },
  { code: '9492Z', label: 'Activités des organisations politiques', section: 'S' },
  { code: '9499Z', label: 'Autres organisations fonctionnant par adhésion volontaire', section: 'S' },
  { code: '9511Z', label: 'Réparation d\'ordinateurs et d\'équipements périphériques', section: 'S' },
  { code: '9512Z', label: 'Réparation d\'équipements de communication', section: 'S' },
  { code: '9521Z', label: 'Réparation de produits électroniques grand public', section: 'S' },
  { code: '9529Z', label: 'Réparation d\'autres biens personnels et domestiques', section: 'S' },
  { code: '9601A', label: 'Blanchisserie-teinturerie de gros', section: 'S' },
  { code: '9601B', label: 'Blanchisserie-teinturerie de détail', section: 'S' },
  { code: '9602A', label: 'Coiffure', section: 'S' },
  { code: '9602B', label: 'Soins de beauté', section: 'S' },
  { code: '9603Z', label: 'Services funéraires', section: 'S' },
  { code: '9604Z', label: 'Entretien corporel', section: 'S' },
  { code: '9609Z', label: 'Autres services personnels n.c.a.', section: 'S' },
]
