// <auto-generated />
using System;
using MAAT.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MAAT.Infrastructure.Migrations
{
    [DbContext(typeof(MaatDbContext))]
    [Migration("20260726214111_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MAAT.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region");

                    b.Property<string>("SectorCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("sector_code");

                    b.Property<string>("Siret")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("siret");

                    b.Property<string>("SizeRange")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("size_range");

                    b.HasKey("Id");

                    b.HasIndex("Siret")
                        .IsUnique();

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.Diagnostic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("GlobalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("global_score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("diagnostics", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.DiagnosticRecommendation", b =>
                {
                    b.Property<Guid>("DiagnosticId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnostic_id");

                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<int>("PriorityRank")
                        .HasColumnType("integer")
                        .HasColumnName("priority_rank");

                    b.HasKey("DiagnosticId", "RecommendationId");

                    b.HasIndex("RecommendationId");

                    b.ToTable("diagnostic_recommendations", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.DomainScore", b =>
                {
                    b.Property<Guid>("DiagnosticId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnostic_id");

                    b.Property<string>("Domain")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("domain");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("score");

                    b.Property<decimal>("SectorWeight")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("sector_weight");

                    b.HasKey("DiagnosticId", "Domain");

                    b.ToTable("domain_scores", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("domain");

                    b.Property<string>("EcovadisRef")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ecovadis_ref");

                    b.Property<string>("GriRef")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("gri_ref");

                    b.Property<string>("HelpText")
                        .HasColumnType("text")
                        .HasColumnName("help_text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("IsoRef")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("iso_ref");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("VsmeRef")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vsme_ref");

                    b.Property<decimal>("Weight")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.ToTable("questions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000001"),
                            Code = "ENV-01",
                            DisplayOrder = 1,
                            Domain = "Environmental",
                            GriRef = "305-1",
                            HelpText = "Le scope 1 couvre les émissions directes (véhicules, chaudières), le scope 2 les émissions liées à l'électricité achetée.",
                            IsActive = true,
                            IsoRef = "6.5.5",
                            Text = "Mesurez-vous et suivez-vous vos émissions de gaz à effet de serre (scope 1 et 2) ?",
                            VsmeRef = "B3",
                            Weight = 3.00m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000002"),
                            Code = "ENV-02",
                            DisplayOrder = 2,
                            Domain = "Environmental",
                            HelpText = "Il peut s'agir d'objectifs chiffrés, d'un suivi des consommations ou d'investissements en efficacité énergétique.",
                            IsActive = true,
                            Text = "Avez-vous mis en place un plan de réduction de votre consommation d'énergie ?",
                            VsmeRef = "B4",
                            Weight = 2.00m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000003"),
                            Code = "ENV-03",
                            DisplayOrder = 3,
                            Domain = "Environmental",
                            GriRef = "306-2",
                            HelpText = "Valoriser signifie recycler, réemployer ou faire traiter les déchets par une filière dédiée plutôt que les envoyer en décharge.",
                            IsActive = true,
                            Text = "Triez-vous et valorisez-vous vos déchets d'activité ?",
                            VsmeRef = "B7",
                            Weight = 1.00m
                        });
                });

            modelBuilder.Entity("MAAT.Domain.Entities.Recommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action_text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("DetailText")
                        .HasColumnType("text")
                        .HasColumnName("detail_text");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("domain");

                    b.Property<string>("EffortLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("effort_level");

                    b.Property<decimal>("ImpactPoints")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("impact_points");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("TriggerMaxValue")
                        .HasColumnType("integer")
                        .HasColumnName("trigger_max_value");

                    b.Property<string>("TriggerQuestionCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("trigger_question_code");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("TriggerQuestionCode");

                    b.ToTable("recommendations", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DiagnosticId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnostic_id");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("format");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<Guid>("GeneratedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("generated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosticId");

                    b.HasIndex("GeneratedByUserId");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.Response", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<Guid>("DiagnosticId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnostic_id");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("DiagnosticId", "QuestionId")
                        .IsUnique();

                    b.ToTable("responses", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.SectorWeight", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("domain");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("SectorCode")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("sector_code");

                    b.Property<decimal>("Weight")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .IsUnique()
                        .HasDatabaseName("IX_sector_weights_default_domain")
                        .HasFilter("is_default");

                    b.HasIndex("SectorCode", "Domain")
                        .IsUnique();

                    b.ToTable("sector_weights", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            Domain = "Environmental",
                            IsDefault = true,
                            Weight = 0.200m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            Domain = "Social",
                            IsDefault = true,
                            Weight = 0.200m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            Domain = "Ethics",
                            IsDefault = true,
                            Weight = 0.200m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000004"),
                            Domain = "Procurement",
                            IsDefault = true,
                            Weight = 0.200m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000005"),
                            Domain = "Governance",
                            IsDefault = true,
                            Weight = 0.200m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000001"),
                            Domain = "Environmental",
                            IsDefault = false,
                            SectorCode = "4941A",
                            Weight = 0.400m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000002"),
                            Domain = "Social",
                            IsDefault = false,
                            SectorCode = "4941A",
                            Weight = 0.200m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000003"),
                            Domain = "Ethics",
                            IsDefault = false,
                            SectorCode = "4941A",
                            Weight = 0.150m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000004"),
                            Domain = "Procurement",
                            IsDefault = false,
                            SectorCode = "4941A",
                            Weight = 0.150m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000005"),
                            Domain = "Governance",
                            IsDefault = false,
                            SectorCode = "4941A",
                            Weight = 0.100m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000001"),
                            Domain = "Environmental",
                            IsDefault = false,
                            SectorCode = "6202A",
                            Weight = 0.100m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000002"),
                            Domain = "Social",
                            IsDefault = false,
                            SectorCode = "6202A",
                            Weight = 0.300m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000003"),
                            Domain = "Ethics",
                            IsDefault = false,
                            SectorCode = "6202A",
                            Weight = 0.250m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000004"),
                            Domain = "Procurement",
                            IsDefault = false,
                            SectorCode = "6202A",
                            Weight = 0.150m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000005"),
                            Domain = "Governance",
                            IsDefault = false,
                            SectorCode = "6202A",
                            Weight = 0.200m
                        });
                });

            modelBuilder.Entity("MAAT.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.Diagnostic", b =>
                {
                    b.HasOne("MAAT.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MAAT.Domain.Entities.DiagnosticRecommendation", b =>
                {
                    b.HasOne("MAAT.Domain.Entities.Diagnostic", null)
                        .WithMany()
                        .HasForeignKey("DiagnosticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MAAT.Domain.Entities.Recommendation", null)
                        .WithMany()
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MAAT.Domain.Entities.DomainScore", b =>
                {
                    b.HasOne("MAAT.Domain.Entities.Diagnostic", null)
                        .WithMany()
                        .HasForeignKey("DiagnosticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MAAT.Domain.Entities.Recommendation", b =>
                {
                    b.HasOne("MAAT.Domain.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("TriggerQuestionCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MAAT.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("MAAT.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MAAT.Domain.Entities.Report", b =>
                {
                    b.HasOne("MAAT.Domain.Entities.Diagnostic", null)
                        .WithMany()
                        .HasForeignKey("DiagnosticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MAAT.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("GeneratedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MAAT.Domain.Entities.Response", b =>
                {
                    b.HasOne("MAAT.Domain.Entities.Diagnostic", null)
                        .WithMany()
                        .HasForeignKey("DiagnosticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MAAT.Domain.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MAAT.Domain.Entities.User", b =>
                {
                    b.HasOne("MAAT.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
