// <auto-generated />
using System;
using MAAT.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MAAT.Infrastructure.Migrations
{
    [DbContext(typeof(MaatDbContext))]
    [Migration("20260921131121_AddRseIndicators")]
    partial class AddRseIndicators
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MAAT.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region");

                    b.Property<string>("SectorCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("sector_code");

                    b.Property<string>("Siret")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("siret");

                    b.Property<string>("SizeRange")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("size_range");

                    b.HasKey("Id");

                    b.HasIndex("Siret")
                        .IsUnique();

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.Diagnostic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("DefaultSectorWeightingApplied")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("default_sector_weighting_applied");

                    b.Property<decimal?>("GlobalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("global_score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("diagnostics", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.DiagnosticRecommendation", b =>
                {
                    b.Property<Guid>("DiagnosticId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnostic_id");

                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<int>("PriorityRank")
                        .HasColumnType("integer")
                        .HasColumnName("priority_rank");

                    b.HasKey("DiagnosticId", "RecommendationId");

                    b.HasIndex("RecommendationId");

                    b.ToTable("diagnostic_recommendations", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.DomainScore", b =>
                {
                    b.Property<Guid>("DiagnosticId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnostic_id");

                    b.Property<string>("Domain")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("domain");

                    b.Property<decimal>("Denominator")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("denominator");

                    b.Property<decimal>("Numerator")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("numerator");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("score");

                    b.Property<decimal>("SectorWeight")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("sector_weight");

                    b.HasKey("DiagnosticId", "Domain");

                    b.ToTable("domain_scores", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("email_verification_tokens", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("domain");

                    b.Property<string>("EcovadisRef")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ecovadis_ref");

                    b.Property<string>("GriRef")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("gri_ref");

                    b.Property<string>("HelpText")
                        .HasColumnType("text")
                        .HasColumnName("help_text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("IsoRef")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("iso_ref");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("VsmeRef")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vsme_ref");

                    b.Property<decimal>("Weight")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.Recommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action_text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("DetailText")
                        .HasColumnType("text")
                        .HasColumnName("detail_text");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("domain");

                    b.Property<string>("EffortLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("effort_level");

                    b.Property<decimal>("ImpactPoints")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("impact_points");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("TriggerMaxValue")
                        .HasColumnType("integer")
                        .HasColumnName("trigger_max_value");

                    b.Property<string>("TriggerQuestionCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("trigger_question_code");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("TriggerQuestionCode");

                    b.ToTable("recommendations", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DiagnosticId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnostic_id");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("format");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<Guid>("GeneratedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("generated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosticId");

                    b.HasIndex("GeneratedByUserId");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.Response", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<Guid>("DiagnosticId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnostic_id");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("DiagnosticId", "QuestionId")
                        .IsUnique();

                    b.ToTable("responses", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.RseIndicators", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ActiveSuppliersCount")
                        .HasColumnType("integer")
                        .HasColumnName("active_suppliers_count");

                    b.Property<double?>("Co2EmissionsTons")
                        .HasColumnType("double precision")
                        .HasColumnName("co2_emissions_tons");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double?>("EmployeeCountFte")
                        .HasColumnType("double precision")
                        .HasColumnName("employee_count_fte");

                    b.Property<double?>("EnergyConsumptionKwh")
                        .HasColumnType("double precision")
                        .HasColumnName("energy_consumption_kwh");

                    b.Property<double?>("ExportRevenuePct")
                        .HasColumnType("double precision")
                        .HasColumnName("export_revenue_pct");

                    b.Property<double?>("GenderEqualityIndex")
                        .HasColumnType("double precision")
                        .HasColumnName("gender_equality_index");

                    b.Property<double?>("LocalSuppliersPct")
                        .HasColumnType("double precision")
                        .HasColumnName("local_suppliers_pct");

                    b.Property<double?>("PermanentContractPct")
                        .HasColumnType("double precision")
                        .HasColumnName("permanent_contract_pct");

                    b.Property<double?>("RecyclingRatePct")
                        .HasColumnType("double precision")
                        .HasColumnName("recycling_rate_pct");

                    b.Property<double?>("RenewableEnergyPct")
                        .HasColumnType("double precision")
                        .HasColumnName("renewable_energy_pct");

                    b.Property<double?>("RevenueEur")
                        .HasColumnType("double precision")
                        .HasColumnName("revenue_eur");

                    b.Property<double?>("RseAssessedSuppliersPct")
                        .HasColumnType("double precision")
                        .HasColumnName("rse_assessed_suppliers_pct");

                    b.Property<double?>("RseInvestmentEur")
                        .HasColumnType("double precision")
                        .HasColumnName("rse_investment_eur");

                    b.Property<double?>("TrainingHoursPerEmployee")
                        .HasColumnType("double precision")
                        .HasColumnName("training_hours_per_employee");

                    b.Property<double?>("TurnoverRatePct")
                        .HasColumnType("double precision")
                        .HasColumnName("turnover_rate_pct");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<double?>("WasteTons")
                        .HasColumnType("double precision")
                        .HasColumnName("waste_tons");

                    b.Property<double?>("WaterConsumptionM3")
                        .HasColumnType("double precision")
                        .HasColumnName("water_consumption_m3");

                    b.Property<double?>("WorkAccidentRate")
                        .HasColumnType("double precision")
                        .HasColumnName("work_accident_rate");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Year")
                        .IsUnique();

                    b.ToTable("rse_indicators", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.SectorWeight", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("domain");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("SectorCode")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("sector_code");

                    b.Property<decimal>("Weight")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .IsUnique()
                        .HasDatabaseName("IX_sector_weights_default_domain")
                        .HasFilter("is_default");

                    b.HasIndex("SectorCode", "Domain")
                        .IsUnique();

                    b.ToTable("sector_weights", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.SupportTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("description");

                    b.Property<int>("GithubIssueNumber")
                        .HasColumnType("integer")
                        .HasColumnName("github_issue_number");

                    b.Property<string>("GithubIssueUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("github_issue_url");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ticket_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("support_tickets", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<DateTimeOffset?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.Diagnostic", b =>
                {
                    b.HasOne("MAAT.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MAAT.Domain.Entities.DiagnosticRecommendation", b =>
                {
                    b.HasOne("MAAT.Domain.Entities.Diagnostic", null)
                        .WithMany()
                        .HasForeignKey("DiagnosticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MAAT.Domain.Entities.Recommendation", null)
                        .WithMany()
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MAAT.Domain.Entities.DomainScore", b =>
                {
                    b.HasOne("MAAT.Domain.Entities.Diagnostic", null)
                        .WithMany()
                        .HasForeignKey("DiagnosticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MAAT.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.HasOne("MAAT.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MAAT.Domain.Entities.Recommendation", b =>
                {
                    b.HasOne("MAAT.Domain.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("TriggerQuestionCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MAAT.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("MAAT.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MAAT.Domain.Entities.Report", b =>
                {
                    b.HasOne("MAAT.Domain.Entities.Diagnostic", null)
                        .WithMany()
                        .HasForeignKey("DiagnosticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MAAT.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("GeneratedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MAAT.Domain.Entities.Response", b =>
                {
                    b.HasOne("MAAT.Domain.Entities.Diagnostic", null)
                        .WithMany()
                        .HasForeignKey("DiagnosticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MAAT.Domain.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MAAT.Domain.Entities.User", b =>
                {
                    b.HasOne("MAAT.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
