// <auto-generated />
using System;
using MAAT.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MAAT.Infrastructure.Migrations
{
    [DbContext(typeof(MaatDbContext))]
    partial class MaatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MAAT.Domain.Entities.ActionItemChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<Guid>("DiagnosticId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnostic_id");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("field");

                    b.Property<string>("NewValue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("old_value");

                    b.Property<string>("RecommendationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("recommendation_code");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("DiagnosticId", "RecommendationCode", "ChangedAt");

                    b.ToTable("action_item_changes", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.ActionItemProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("assigned_to");

                    b.Property<Guid>("DiagnosticId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnostic_id");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<string>("RecommendationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("recommendation_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosticId", "RecommendationCode")
                        .IsUnique();

                    b.ToTable("action_item_progress", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region");

                    b.Property<string>("SectorCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("sector_code");

                    b.Property<string>("Siret")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("siret");

                    b.Property<string>("SizeRange")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("size_range");

                    b.HasKey("Id");

                    b.HasIndex("Siret")
                        .IsUnique();

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.CompanyLogo", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<byte[]>("PngContent")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("png_content");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("CompanyId");

                    b.ToTable("company_logos", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.CompanySite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DetectedSensitiveAreas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("detected_sensitive_areas");

                    b.Property<string>("GeocodedLabel")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("geocoded_label");

                    b.Property<bool?>("InOrNearSensitiveArea")
                        .HasColumnType("boolean")
                        .HasColumnName("in_or_near_sensitive_area");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("SensitiveAreaName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("sensitive_area_name");

                    b.Property<DateTimeOffset?>("SensitiveAreasCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sensitive_areas_checked_at");

                    b.Property<string>("Tenure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tenure");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("company_sites", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.Diagnostic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("DefaultSectorWeightingApplied")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("default_sector_weighting_applied");

                    b.Property<decimal?>("GlobalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("global_score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("diagnostics", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.DiagnosticRecommendation", b =>
                {
                    b.Property<Guid>("DiagnosticId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnostic_id");

                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<int>("PriorityRank")
                        .HasColumnType("integer")
                        .HasColumnName("priority_rank");

                    b.HasKey("DiagnosticId", "RecommendationId");

                    b.HasIndex("RecommendationId");

                    b.ToTable("diagnostic_recommendations", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.DomainScore", b =>
                {
                    b.Property<Guid>("DiagnosticId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnostic_id");

                    b.Property<string>("Domain")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("domain");

                    b.Property<decimal>("Denominator")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("denominator");

                    b.Property<decimal>("Numerator")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("numerator");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("score");

                    b.Property<decimal>("SectorWeight")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("sector_weight");

                    b.HasKey("DiagnosticId", "Domain");

                    b.ToTable("domain_scores", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("email_verification_tokens", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("domain");

                    b.Property<string>("EcovadisRef")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ecovadis_ref");

                    b.Property<string>("GriRef")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("gri_ref");

                    b.Property<string>("HelpText")
                        .HasColumnType("text")
                        .HasColumnName("help_text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("IsoRef")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("iso_ref");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("VsmeRef")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vsme_ref");

                    b.Property<decimal>("Weight")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.Recommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action_text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("DetailText")
                        .HasColumnType("text")
                        .HasColumnName("detail_text");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("domain");

                    b.Property<string>("EffortLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("effort_level");

                    b.Property<decimal>("ImpactPoints")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("impact_points");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("TriggerMaxValue")
                        .HasColumnType("integer")
                        .HasColumnName("trigger_max_value");

                    b.Property<string>("TriggerQuestionCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("trigger_question_code");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("TriggerQuestionCode");

                    b.ToTable("recommendations", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DiagnosticId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnostic_id");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("format");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<Guid>("GeneratedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("generated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosticId");

                    b.HasIndex("GeneratedByUserId");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.Response", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<Guid>("DiagnosticId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnostic_id");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("DiagnosticId", "QuestionId")
                        .IsUnique();

                    b.ToTable("responses", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.RseIndicators", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ActiveSuppliersCount")
                        .HasColumnType("integer")
                        .HasColumnName("active_suppliers_count");

                    b.Property<double?>("Co2EmissionsTons")
                        .HasColumnType("double precision")
                        .HasColumnName("co2_emissions_tons");

                    b.Property<double?>("CollectiveBargainingPct")
                        .HasColumnType("double precision")
                        .HasColumnName("collective_bargaining_pct");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double?>("ElectricityNonRenewableMwh")
                        .HasColumnType("double precision")
                        .HasColumnName("electricity_non_renewable_mwh");

                    b.Property<double?>("ElectricityRenewableMwh")
                        .HasColumnType("double precision")
                        .HasColumnName("electricity_renewable_mwh");

                    b.Property<double?>("EmployeeCountFte")
                        .HasColumnType("double precision")
                        .HasColumnName("employee_count_fte");

                    b.Property<double?>("EnergyConsumptionKwh")
                        .HasColumnType("double precision")
                        .HasColumnName("energy_consumption_kwh");

                    b.Property<double?>("ExportRevenuePct")
                        .HasColumnType("double precision")
                        .HasColumnName("export_revenue_pct");

                    b.Property<double?>("FemaleEmployees")
                        .HasColumnType("double precision")
                        .HasColumnName("female_employees");

                    b.Property<double?>("FuelsNonRenewableMwh")
                        .HasColumnType("double precision")
                        .HasColumnName("fuels_non_renewable_mwh");

                    b.Property<double?>("FuelsRenewableMwh")
                        .HasColumnType("double precision")
                        .HasColumnName("fuels_renewable_mwh");

                    b.Property<double?>("GenderEqualityIndex")
                        .HasColumnType("double precision")
                        .HasColumnName("gender_equality_index");

                    b.Property<double?>("GenderPayGapPct")
                        .HasColumnType("double precision")
                        .HasColumnName("gender_pay_gap_pct");

                    b.Property<double?>("HazardousWasteTons")
                        .HasColumnType("double precision")
                        .HasColumnName("hazardous_waste_tons");

                    b.Property<double?>("HoursWorked")
                        .HasColumnType("double precision")
                        .HasColumnName("hours_worked");

                    b.Property<double?>("LocalSuppliersPct")
                        .HasColumnType("double precision")
                        .HasColumnName("local_suppliers_pct");

                    b.Property<double?>("MaleEmployees")
                        .HasColumnType("double precision")
                        .HasColumnName("male_employees");

                    b.Property<double?>("NonHazardousWasteTons")
                        .HasColumnType("double precision")
                        .HasColumnName("non_hazardous_waste_tons");

                    b.Property<double?>("OtherGenderEmployees")
                        .HasColumnType("double precision")
                        .HasColumnName("other_gender_employees");

                    b.Property<double?>("PermanentContractPct")
                        .HasColumnType("double precision")
                        .HasColumnName("permanent_contract_pct");

                    b.Property<double?>("PermanentEmployees")
                        .HasColumnType("double precision")
                        .HasColumnName("permanent_employees");

                    b.Property<int?>("RecordableAccidents")
                        .HasColumnType("integer")
                        .HasColumnName("recordable_accidents");

                    b.Property<double?>("RecyclingRatePct")
                        .HasColumnType("double precision")
                        .HasColumnName("recycling_rate_pct");

                    b.Property<double?>("RenewableEnergyPct")
                        .HasColumnType("double precision")
                        .HasColumnName("renewable_energy_pct");

                    b.Property<double?>("RevenueEur")
                        .HasColumnType("double precision")
                        .HasColumnName("revenue_eur");

                    b.Property<double?>("RseAssessedSuppliersPct")
                        .HasColumnType("double precision")
                        .HasColumnName("rse_assessed_suppliers_pct");

                    b.Property<double?>("RseInvestmentEur")
                        .HasColumnType("double precision")
                        .HasColumnName("rse_investment_eur");

                    b.Property<double?>("Scope1Tco2e")
                        .HasColumnType("double precision")
                        .HasColumnName("scope1_tco2e");

                    b.Property<double?>("Scope2LocationTco2e")
                        .HasColumnType("double precision")
                        .HasColumnName("scope2_location_tco2e");

                    b.Property<double?>("TemporaryEmployees")
                        .HasColumnType("double precision")
                        .HasColumnName("temporary_employees");

                    b.Property<double?>("TrainingHoursPerEmployee")
                        .HasColumnType("double precision")
                        .HasColumnName("training_hours_per_employee");

                    b.Property<double?>("TurnoverRatePct")
                        .HasColumnType("double precision")
                        .HasColumnName("turnover_rate_pct");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<double?>("WasteTons")
                        .HasColumnType("double precision")
                        .HasColumnName("waste_tons");

                    b.Property<double?>("WaterConsumptionM3")
                        .HasColumnType("double precision")
                        .HasColumnName("water_consumption_m3");

                    b.Property<double?>("WaterConsumptionStressM3")
                        .HasColumnType("double precision")
                        .HasColumnName("water_consumption_stress_m3");

                    b.Property<double?>("WaterWithdrawalM3")
                        .HasColumnType("double precision")
                        .HasColumnName("water_withdrawal_m3");

                    b.Property<double?>("WorkAccidentRate")
                        .HasColumnType("double precision")
                        .HasColumnName("work_accident_rate");

                    b.Property<int?>("WorkFatalities")
                        .HasColumnType("integer")
                        .HasColumnName("work_fatalities");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Year")
                        .IsUnique();

                    b.ToTable("rse_indicators", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.SectorWeight", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("domain");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("SectorCode")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("sector_code");

                    b.Property<decimal>("Weight")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .IsUnique()
                        .HasDatabaseName("IX_sector_weights_default_domain")
                        .HasFilter("is_default");

                    b.HasIndex("SectorCode", "Domain")
                        .IsUnique();

                    b.ToTable("sector_weights", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BillingPeriod")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("billing_period");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("plan");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stripe_customer_id");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stripe_subscription_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.HasIndex("StripeSubscriptionId")
                        .IsUnique();

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.SupportTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("description");

                    b.Property<int>("GithubIssueNumber")
                        .HasColumnType("integer")
                        .HasColumnName("github_issue_number");

                    b.Property<string>("GithubIssueUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("github_issue_url");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ticket_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("support_tickets", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<DateTimeOffset?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.VsmeStatement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("CircularEconomyApplied")
                        .HasColumnType("boolean")
                        .HasColumnName("circular_economy_applied");

                    b.Property<string>("CircularEconomyDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("circular_economy_description");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<int?>("CorruptionConvictions")
                        .HasColumnType("integer")
                        .HasColumnName("corruption_convictions");

                    b.Property<double?>("CorruptionFinesEur")
                        .HasColumnType("double precision")
                        .HasColumnName("corruption_fines_eur");

                    b.PrimitiveCollection<string[]>("CoveredTopics")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("covered_topics");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmployeeCountUnit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("employee_count_unit");

                    b.Property<bool?>("HasFutureInitiatives")
                        .HasColumnType("boolean")
                        .HasColumnName("has_future_initiatives");

                    b.Property<bool?>("HasPolicies")
                        .HasColumnType("boolean")
                        .HasColumnName("has_policies");

                    b.Property<bool?>("HasPractices")
                        .HasColumnType("boolean")
                        .HasColumnName("has_practices");

                    b.Property<bool?>("HasTargets")
                        .HasColumnType("boolean")
                        .HasColumnName("has_targets");

                    b.Property<string>("LegalForm")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_form");

                    b.Property<string>("MaterialFlowsDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("material_flows_description");

                    b.Property<bool?>("MinimumWageMet")
                        .HasColumnType("boolean")
                        .HasColumnName("minimum_wage_met");

                    b.PrimitiveCollection<string[]>("OmittedDisclosures")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("omitted_disclosures");

                    b.Property<bool?>("PoliciesPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("policies_public");

                    b.Property<string>("PollutionReportUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("pollution_report_url");

                    b.Property<bool?>("PollutionReportingApplicable")
                        .HasColumnType("boolean")
                        .HasColumnName("pollution_reporting_applicable");

                    b.Property<string>("PracticesDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("practices_description");

                    b.Property<string>("PrimaryCountry")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("primary_country");

                    b.Property<string>("ReportingBasis")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reporting_basis");

                    b.Property<double?>("TotalAssetsEur")
                        .HasColumnType("double precision")
                        .HasColumnName("total_assets_eur");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Year")
                        .IsUnique();

                    b.ToTable("vsme_statements", (string)null);
                });

            modelBuilder.Entity("MAAT.Domain.Entities.ActionItemChange", b =>
                {
                    b.HasOne("MAAT.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MAAT.Domain.Entities.Diagnostic", null)
                        .WithMany()
                        .HasForeignKey("DiagnosticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MAAT.Domain.Entities.CompanyLogo", b =>
                {
                    b.HasOne("MAAT.Domain.Entities.Company", null)
                        .WithOne()
                        .HasForeignKey("MAAT.Domain.Entities.CompanyLogo", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MAAT.Domain.Entities.CompanySite", b =>
                {
                    b.HasOne("MAAT.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MAAT.Domain.Entities.Diagnostic", b =>
                {
                    b.HasOne("MAAT.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MAAT.Domain.Entities.DiagnosticRecommendation", b =>
                {
                    b.HasOne("MAAT.Domain.Entities.Diagnostic", null)
                        .WithMany()
                        .HasForeignKey("DiagnosticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MAAT.Domain.Entities.Recommendation", null)
                        .WithMany()
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MAAT.Domain.Entities.DomainScore", b =>
                {
                    b.HasOne("MAAT.Domain.Entities.Diagnostic", null)
                        .WithMany()
                        .HasForeignKey("DiagnosticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MAAT.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.HasOne("MAAT.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MAAT.Domain.Entities.Recommendation", b =>
                {
                    b.HasOne("MAAT.Domain.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("TriggerQuestionCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MAAT.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("MAAT.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MAAT.Domain.Entities.Report", b =>
                {
                    b.HasOne("MAAT.Domain.Entities.Diagnostic", null)
                        .WithMany()
                        .HasForeignKey("DiagnosticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MAAT.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("GeneratedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MAAT.Domain.Entities.Response", b =>
                {
                    b.HasOne("MAAT.Domain.Entities.Diagnostic", null)
                        .WithMany()
                        .HasForeignKey("DiagnosticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MAAT.Domain.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MAAT.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("MAAT.Domain.Entities.Company", null)
                        .WithOne()
                        .HasForeignKey("MAAT.Domain.Entities.Subscription", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MAAT.Domain.Entities.User", b =>
                {
                    b.HasOne("MAAT.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MAAT.Domain.Entities.VsmeStatement", b =>
                {
                    b.HasOne("MAAT.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("MAAT.Domain.Entities.VsmeCertification", "Certifications", b1 =>
                        {
                            b1.Property<Guid>("VsmeStatementId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Issuer");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<DateOnly?>("ObtainedOn");

                            b1.Property<string>("Rating");

                            b1.HasKey("VsmeStatementId", "__synthesizedOrdinal");

                            b1.ToTable("vsme_statements");

                            b1
                                .ToJson("certifications")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("VsmeStatementId");
                        });

                    b.OwnsMany("MAAT.Domain.Entities.VsmeCountryHeadcount", "EmployeesByCountry", b1 =>
                        {
                            b1.Property<Guid>("VsmeStatementId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Country")
                                .IsRequired();

                            b1.Property<double>("Employees");

                            b1.HasKey("VsmeStatementId", "__synthesizedOrdinal");

                            b1.ToTable("vsme_statements");

                            b1
                                .ToJson("employees_by_country")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("VsmeStatementId");
                        });

                    b.OwnsMany("MAAT.Domain.Entities.VsmePollutant", "Pollutants", b1 =>
                        {
                            b1.Property<Guid>("VsmeStatementId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Medium")
                                .IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<double>("Quantity");

                            b1.Property<string>("Unit")
                                .IsRequired();

                            b1.HasKey("VsmeStatementId", "__synthesizedOrdinal");

                            b1.ToTable("vsme_statements");

                            b1
                                .ToJson("pollutants")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("VsmeStatementId");
                        });

                    b.OwnsMany("MAAT.Domain.Entities.VsmeSubsidiary", "Subsidiaries", b1 =>
                        {
                            b1.Property<Guid>("VsmeStatementId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<string>("RegisteredAddress")
                                .IsRequired();

                            b1.HasKey("VsmeStatementId", "__synthesizedOrdinal");

                            b1.ToTable("vsme_statements");

                            b1
                                .ToJson("subsidiaries")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("VsmeStatementId");
                        });

                    b.Navigation("Certifications");

                    b.Navigation("EmployeesByCountry");

                    b.Navigation("Pollutants");

                    b.Navigation("Subsidiaries");
                });
#pragma warning restore 612, 618
        }
    }
}
